### ISSUE TITLE
Monofoxe Credit

### ISSUE THREAD

**Issue by Martenfur** [MonoGo-Engine/MonoGo#4]
Just a suggestion, instead of doing an off-brand Monofoxe, you could just contribute to the real thing. ;)

Also at the very least mention that you've based this on Monofoxe, like, for real.

**Comment by BlizzCrafter** [comment]
Hey @Martenfur! 

Nice that you found your way to this project. I really like your foundational work of the Monofoxe engine and wanted to build upon that. I noticed that what I had in mind for my own abstraction of your engine would be fundamentally different from yours, so I decided to start my own project. I also plan to remove some core elements of Monofoxe mid-therm and I am pretty sure that this is not in your interest.

The Readme of your Monofoxe engine sais:

"Monofoxe is licensed under MIT, so you can use it and its code in any shenanigans you want. Free games, commercial games, **your own the-coolest-in-the-world engines** - no payment or royalties required."

And:

"Just please leave a credit. ; - )"

What I did in the [License.txt](https://github.com/MonoGo-Engine/MonoGo/blob/master/LICENSE.txt) file of my project if you look closely.

I even have a "monofoxe" tag in the upper right repo description. 

Reading the Readme file of your project, I thought I credited you in the right way. Please let my know if you want to be credited in a different way and I will of course do that.

---

"you could just contribute to the real thing."

But... I did...: https://github.com/Martenfur/Monofoxe/pull/26

Btw: Are you still working activley on Monofoxe? It seemed to be on halt for a while. 

Cheers!

**Comment by BlizzCrafter** [comment]
Okay, I agree on that. Thats why I just added a "Credits" section via https://github.com/MonoGo-Engine/MonoGo/commit/7d11e3496afe02b4c016ba9e43336fa6ef7ad4ad

Here:
https://github.com/MonoGo-Engine/MonoGo?tab=readme-ov-file#credits

---

> can't just launch samples off of your develop branch without compiling nugets first and linking them locally.

Yeah, first I don't wanted to do that neither. But now I have a local setup which works. It is just a seperate .sln file which hooks up the samples project and references the engine libs instead of nugets and such. I will see how long that lasts :)

> Current state of Monofoxe is in support.

Ah, thanks for letting me know. I will surly stop by from time to time and see how your engine evolves. Of course I would contribute again if I see something fit in.

Thanks for creating Monofoxe and keep going!
